### ISSUE TITLE
Unify indentation in configuration files

### ISSUE THREAD

**Issue by vdusek** [apify/apify-client-python#139]
Some of our configuration files currently use 2 space indent and others use 4 space indent.

Let's unify this and use the same indent (2 spaces) for all configuration files (`yaml`, `toml`, `ini`/`cfg`, ...).

**Comment by B4nan** [comment]
I'd vote to actually unify this and use the same 4 spaces as we use for other languages.

Even better, I'd vote to adopt tabs instead, so users can choose how long the indent should be...

**Comment by vdusek** [comment]
I don't have a strong preference if 2 or 4 in most cases.

However, YAML files can have pretty deep nesting. 

Here is an example from our real GH actions YAML conf:

```yaml
# 2 space indentation
jobs:
  apify-pr-toolkit:
    runs-on: ubuntu-latest
    steps:
      - name: run pull-request-toolkit action
        uses: apify/pull-request-toolkit-action@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          org-token: ${{ secrets.PULL_REQUEST_TOOLKIT_ACTION_GITHUB_TOKEN }}
          zenhub-token: ${{ secrets.PULL_REQUEST_TOOLKIT_ACTION_ZENHUB_TOKEN }}
```


```yaml
# 4 space indentation
jobs:
    apify-pr-toolkit:
        runs-on: ubuntu-latest
        steps:
            - name: run pull-request-toolkit action
              uses: apify/pull-request-toolkit-action@main
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  org-token: ${{ secrets.PULL_REQUEST_TOOLKIT_ACTION_GITHUB_TOKEN }}
                  zenhub-token: ${{ secrets.PULL_REQUEST_TOOLKIT_ACTION_ZENHUB_TOKEN }}
```

So in the YAML case, I'd slightly prefer to stay with 2. For all other formats (`ini`/`cfg`, `toml`, `json`) I don't mind if we use 2 or 4.

In the case of choosing between tabs and spaces. In the Python world, space indentation is generally preferred over tabs ([PEP 8 | Tabs or Spaces?](https://peps.python.org/pep-0008/#tabs-or-spaces)). Since we're talking about configuration files in the Python projects, I'd stay with the space indentation as well.

@fnesveda what's your opinion?
